### ISSUE TITLE
Overlay for Android below 6.0

### ISSUE THREAD

**Issue by sanga000** [antest1/kcanotify#12]
It seems that the battle overlay does not work for android versions below 6.0
I am thinking that this can actually be done using a similar method as PuzzCombo for Puzzle and Dragons (which also uses screen overlay, and works for Android 4.0+)

**Comment by antest1** [comment]
Overlay works for below 6.0. BattleView worked for device with android 4.1.2 in previous versions of kcanotify, and since the core code for it is not changed so it should work with at least above Jellybean. (I'll check it again.)

I think there would be another problem for that problem. 
What is your device's model name and android version?

**Comment by sanga000** [comment]
I'll check the permission again in this case, it is possible that the permission switched itself off by default

**Comment by antest1** [comment]
I checked that screen overlay works for android 4.4.2(Kitkat).

**Comment by antest1** [comment]
Since there are no other report with this problem, I'll close the issue.
Please re-open this issue when same problem occurs.
