### ISSUE TITLE
2.3.1 rev5 bug feedback

### ISSUE THREAD

**Issue by skysumbra** [antest1/kcanotify#13]
This version addition tradition language for mission list  context error,it's display korea language.

**Comment by antest1** [comment]
Mission means expedition? can you give me some example (like screenshot?)

**Comment by skysumbra** [comment]
picture display
https://upload.cc/i/n5b9Ki.jpeg

**Comment by antest1** [comment]
It seems that there is an error when processing quest data. (That is a default layout data)

I have no problem with the tcn language settings(https://upload.cc/i/KsXhdS.png) and there was no other report related with this problem, so I think there would be another reason for this problem.

Is this bug always occurs when using QuestView? can you tell me what quests are in that page(1/7)?

**Comment by skysumbra** [comment]
I try again question list,only ALL (全) category have problem,other category normal.

**Comment by antest1** [comment]
okay, the problem was the translation data([quest-tcn.json](https://github.com/antest1/kcanotify/blob/v2.3.1r5/app/src/main/assets/quests-scn.json)).
some of quests lacks quest code(key `code`), so the error occurred while reading translation data. 

I'll update the code for quests which does not have code key.

**Comment by antest1** [comment]
fixed in b7138f4. close this issue.
