### ISSUE TITLE
Error when loading from storage (using default data)

### ISSUE THREAD

**Issue by takaizu91** [antest1/kcanotify#62]
I get this error when I turned on the kcanotify service and it keep notify me of said error whenever I went to kcanofity menu

Didn't found any issue yet of what could impact the game so far. Just curious why this error occur

**Comment by antest1** [comment]
This error happens when kcanotify fails to load the data from the storage. This sometimes happens when there exist some problem while downloading. 

You can check the error log to know what file triggered the error.
To resolve this error, download the problematic resource again, and exit and restart the kcanotify app.

**Comment by antest1** [comment]
Oh my god, the reason was really data error (quest-tcn.json).
I'll update the new resource, so please wait.

**Comment by takaizu91** [comment]
Okay, new resource updated and I restarted the app just in case. So far, no error on my end. Good work @antest1
